### ISSUE TITLE
请问这个怎么结合react-native-video使用呢

### ISSUE THREAD

**Issue by Yunnathai** [ykln/react-native-video-gesture#1]
请问这个怎么结合react-native-video使用呢

**Comment by ykln** [comment]
使用ref 
react-native-video 有个seek的方法可以直接设置进度
建议你在onProgressEnd方法里设置，不过这个方法的参数是小数，具体对应的跳转到视频的进度需要你自己算

**Comment by Yunnathai** [comment]
好的 谢谢。
